### ISSUE TITLE
files missing to run the server_run.py

### ISSUE THREAD

**Issue by shlyakh** [dhilgart/TWIML_codenames#1]
It looks like wordlist.txt not under source control. Also need to add fastapi to requitements.txt

**Comment by dhilgart** [comment]
Yeah, I want to keep the wordlist secret until competition time. No one should need to run server_run.py except me when I push it to Heroku, so I'm keeping wordlist.txt on my local machine. Also, fastapi is only needed for the server, not for the clients, so it is in the Dockerfile rather than requirements.txt. (requirements.txt is for the clients)
